name: Build Screencap DLL

on:
  workflow_dispatch:
#  push:
#    tags:
#      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Install vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: bb4f525cbddd409bdc714ee3043b15ff7766af59

      - name: Install OpenCV (static)
        run: |
          vcpkg install opencv:x64-windows-static

      - name: Configure CMake (Release)
        run: |
          cmake --preset release `
            -DCMAKE_TOOLCHAIN_FILE="${env:VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: |
          cmake --build --preset release

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: Screencap-dll
          path: bin/Screencap.dll
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/Screencap.dll
